export const LOAD_ALL_PRODUCTS_SUCCESS = 'LOAD_ALL_PRODUCTS_SUCCESS';
export const LOAD_ALL_PRODUCTS_FAILURE = 'LOAD_ALL_PRODUCTS_FAILURE';

export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS'
export const GET_DETAIL_PRODUCT_FAILURE = 'GET_DETAIL_PRODUCT_FAILURE'


export const GET_PAGES = 'GET_PAGES';

